#! /bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

# exchange monitor positon right to left(default left to right)
#bspc monitor eDP-1 -s HDMI-2

# query monitor name
#monitor=$(bspc query -M --names)

# auto adjust one or two monitor display
hdmi2isconnected="`xrandr -q | awk '/HDMI-2 connected/'`"
if [ "$hdmi2isconnected" != "" ]; then
    bspc monitor eDP-1 -d I II III IV V
    bspc monitor HDMI-2 -d VI VII VIII IX X
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

# display style config
bspc config border_width         1
bspc config window_gap           2
bspc config top_padding         12
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true


# displya ruler config
bspc rule -a Boostnote desktop='^1'
bspc rule -a Wps desktop='^1'
bspc rule -a Et desktop='^1'
bspc rule -a Wpp desktop='^1'
bspc rule -a "Foxit Reader" desktop='^1'
bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp state=floating follow=on desktop='^2'
bspc rule -a jetbrains-idea desktop='^3'
bspc rule -a Forticlientsslvpn desktop='^9'
bspc rule -a "VirtualBox Manager" desktop='^10'
bspc rule -a "VirtualBox Machine" desktop='^10'
bspc rule -a copyq state=floating follow=on
bspc rule -a Screenkey manage=off



